apiVersion: v1
kind: ConfigMap
metadata:
  name: php-config
data:
  php-custom.ini: |-
    display_errors = Off
    display_startup_errors = Off
    error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
    log_errors = On
    upload_max_filesize = 8M
    memory_limit = 1024
    post_max_size = 50M
 